### ISSUE TITLE
Where is the codes of  Flash Attention 2 and QLoRA?

### ISSUE THREAD

**Issue by shushengyuan** [Alpha-VLLM/LLaMA2-Accessory#27]
Could you show us any example?

**Comment by kriskrisliu** [comment]
We are currently engaged in the process of quantization (QLoRA) and will be updating the repository soon. 
You can get a sneak peek here: https://github.com/kriskrisliu/LLaMA2-Accessory.
If you encounter any bugs, please feel free to leave your comments here.
It is easy to use, for example, if we running `single_turn.py` script for single-turn dialogues:
```bash
# FP16 inference. 26GB of VRAM is required for the 7B model.
python demos/single_turn.py \
--llama_config /path/to/params.json --tokenizer_path /path/to/tokenizer.model \
--pretrained_path /path/to/finetuned

# (Optional) Quantization-assistant Inference. To run on GPUs with limited VRAM, add the "--quant" flag.
# For example, less than 7GB of VRAM is required for the 7B model.
python demos/single_turn.py <--some_flags> --quant
```

**Comment by shushengyuan** [comment]
Thx, it's very nice

**Comment by kai-wen-yang** [comment]
Can you please provide mutimodal 7b checkpoint such as alpacaLlava_llamaQformerv2_7b and alpacaLlava_llamaQformerv2Peft_7b? @kriskrisliu

**Comment by kriskrisliu** [comment]
> Can you please provide mutimodal 7b checkpoint such as alpacaLlava_llamaQformerv2_7b and alpacaLlava_llamaQformerv2Peft_7b? @kriskrisliu

Apologies, but I have not trained a 7B model. If you're searching for an alternative, you might consider quantizing a 13B multi-modal model. This method can substantially reduce memory usage to around 12GB for inference. For details, please check the main branch as we have supported quantization recently.
It is simple to use. Add `--quant` flag when inference, for example:
```bash
torchrun --nproc-per-node=1 demos/single_turn_mm.py \
--llama_config path/to/params.json \
--tokenizer_path path/to/tokenizer.model \
--pretrained_path path/to/finetuned/model \
--quant 

```

**Comment by kai-wen-yang** [comment]
Hi, @kriskrisliu, I try to train  a LLaMA2-7B on Alpaca using --quant.
```
torchrun --master_port=1112 --nproc_per_node=6 main_finetune.py --quant \
--output_dir output/"$exp_name" --epochs 4 --warmup_epochs 1 \
--batch_size 4 --accum_iter 2 --num_workers 4 \
--max_words 512 \
--lr 0.00003 --min_lr 0.000005 --clip_grad 2 --weight_decay 0.02 \
--data_parallel "$data_parallel" --model_parallel_size "$model_parallel" --checkpointing \
--llama_type llama --llama_config "$llama_config" --tokenizer_path "$tokenizer_path" \
--no_visual \
--pretrained_path "$pretrained_path" --pretrained_type="$pretrained_type" \
--data_config $data_config \
2>&1 | tee -a output/"$exp_name"/output.log
```
But it raises an error:
```
Traceback (most recent call last):
  File "main_finetune.py", line 340, in <module>
    main(args)
  File "main_finetune.py", line 215, in main
    model = FSDP(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 391, in __init__
    _auto_wrap(auto_wrap_kwargs, fsdp_kwargs, FullyShardedDataParallel)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/_wrap_utils.py", line 73, in _auto_wrap
    _recursive_wrap(**auto_wrap_kwargs, **fsdp_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/wrap.py", line 370, in _recursive_wrap
    wrapped_child, num_wrapped_params = _recursive_wrap(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/wrap.py", line 370, in _recursive_wrap
    wrapped_child, num_wrapped_params = _recursive_wrap(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/wrap.py", line 370, in _recursive_wrap
    wrapped_child, num_wrapped_params = _recursive_wrap(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/wrap.py", line 388, in _recursive_wrap
    return _wrap(module, wrapper_cls, **kwargs), nonwrapped_numel
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/wrap.py", line 317, in _wrap
    return wrapper_cls(module, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 408, in __init__
    _init_param_handle_from_module(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/_init_utils.py", line 429, in _init_param_handle_from_module
    _init_param_handle_from_params(state, managed_params, fully_sharded_module)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/_init_utils.py", line 525, in _init_param_handle_from_params
    handle = FlatParamHandle(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/flat_param.py", line 366, in __init__
    self._init_flat_param(params, fully_sharded_module, use_orig_params)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/flat_param.py", line 435, in _init_flat_param
    raise ValueError("Integer parameters are unsupported")
ValueError: Integer parameters are unsupported
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 134008) of binary: /opt/conda/bin/python

    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/wrap.py", line 388, in _recursive_wrap                                                                                       [26/1881]
    return _wrap(module, wrapper_cls, **kwargs), nonwrapped_numel
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/wrap.py", line 317, in _wrap
    return wrapper_cls(module, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 408, in __init__
    _init_param_handle_from_module(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/_init_utils.py", line 429, in _init_param_handle_from_module
    _init_param_handle_from_params(state, managed_params, fully_sharded_module)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/_init_utils.py", line 525, in _init_param_handle_from_params
    handle = FlatParamHandle(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/flat_param.py", line 366, in __init__
    self._init_flat_param(params, fully_sharded_module, use_orig_params)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/fsdp/flat_param.py", line 435, in _init_flat_param
    raise ValueError("Integer parameters are unsupported")
ValueError: Integer parameters are unsupported
```

**Comment by kriskrisliu** [comment]
--llama_type should be "llama_peft" when using quantization. Please check the document where we show examples of how to run with quantization. https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/main/docs/finetune.md#quantization-assisted-parameter-efficient-fine-tuning
