### ISSUE TITLE
model.LLM.llama_qformerv2_peft.Transformer can not load

### ISSUE THREAD

**Issue by WeiXuanLi-1024** [Alpha-VLLM/LLaMA2-Accessory#72]
when I run the script "alpacaLlava_llamaQformerv2Peft_QF_13B.sh" 
this error occurred :   
`dist_backend='nccl')
[09:51:49.180219] Start initialization.
[09:51:49.180394] ## Processing on RANK 0.
[09:51:49.180664] <class 'model.LLM.llama_qformerv2_peft.Transformer'>
[09:51:49.189299] Model Args:
 ModelArgs(dim=4096, n_layers=32, n_heads=32, n_kv_heads=None, vocab_size=32000, multiple_of=256, ffn_dim_multiplier=None, norm_eps=1e-05, rope_theta=10000, max_batch_size=32, max_seq_len=512, rope_scaling=None, lora_rank=16, bias_tuning=True)
[09:52:32.216106] rope theta: 10000
[09:52:32.217181] build llama model with qformerv2
Traceback (most recent call last):
  File "/home/liwx/anaconda3/envs/accessory/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/liwx/anaconda3/envs/accessory/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/liwx/anaconda3/envs/accessory/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liwx/anaconda3/envs/accessory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/liwx/anaconda3/envs/accessory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/home/liwx/anaconda3/envs/accessory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/home/liwx/anaconda3/envs/accessory/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/liwx/anaconda3/envs/accessory/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fb338344df0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurr`

I test the network ：
PING www.a.shifen.com (153.3.238.102) 56(84) bytes of data.
64 bytes from 153.3.238.102 (153.3.238.102): icmp_seq=1 ttl=53 time=3.47 ms
64 bytes from 153.3.238.102 (153.3.238.102): icmp_seq=2 ttl=53 time=3.73 ms
64 bytes from 153.3.238.102 (153.3.238.102): icmp_seq=3 ttl=53 time=3.46 ms

I need climb over the wall to download this model?

**Comment by ChrisLiu6** [comment]
Our multi-modal models need pre-trained weights for the visual encoder. The following code downloads the pre-trained blip2 model from HuggingFace
https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/f6a1525f59e6c16a87258734ceeb1b06d1b948b6/accessory/model/LLM/llama_qformerv2_peft.py#L291

**Comment by WeiXuanLi-1024** [comment]
> Our multi-modal models need pre-trained weights for the visual encoder. The following code downloads the pre-trained blip2 model from HuggingFace
> 
> https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/f6a1525f59e6c16a87258734ceeb1b06d1b948b6/accessory/model/LLM/llama_qformerv2_peft.py#L291
> 
> Please check if you can access huggingface, or proxy may be needed.

Thanks for your reply, I have solved this problem by downloading offline mode from huggingface 
but I have another problem, I want to Fine-Tuning with Quantization refer to link https://llama2-accessory.readthedocs.io/en/latest/finetune/quantization.html  ,the script alpacaLlava_llamaQformerv2Peft_QF_13B.sh 
![ec8dfbe277f668cb613cb8e2c865b6e](https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/24350444/b55892b9-0dbb-4ad9-808f-d1909e0242b9)
pretrained_path points to  download from here  stage_1 checkpoint  https://huggingface.co/Alpha-VLLM/LLaMA2-Accessory/tree/main/finetune/mm/caption_llamaQformerv2_13b
when i run the exps ,this error occurred :
![e8618420d8d7308c6f99afefb23f637](https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/24350444/30e71a40-ea5d-40b7-bc06-2fc0990c6422)

**Comment by kriskrisliu** [comment]
The error shows that the model you've loaded is not compatible to the checkpoint.
Please have a look in Line 5, pass llama2-13B param.json file to the flag: 
`llama_config="<path/to/llama2-13B/param.json> configs/model/finetune/sg/llamaPeft_normBiasLora.json"`
In this way you will init a 13B-like model to load the 13B checkpoint.

**Comment by WeiXuanLi-1024** [comment]
this link is right for  llama2-13B param.json file ?
https://huggingface.co/Alpha-VLLM/LLaMA2-Accessory/blob/main/config/13B_params.json

I have one more question 
![a23fdcf6a9b7ef26d9dff57d3aff645](https://github.com/Alpha-VLLM/LLaMA2-Accessory/assets/24350444/9fac477c-14d0-4383-a3e3-ed41d67f44b3)
 what is difference between alpacaLlava_llamaQformerv2Peft_13b  and  alpacaLlava_llamaQformerv2_13b ?
